# Branch Protection Rules Configuration
#
# This file configures GitHub branch protection rules to enforce security requirements 
# for the Phoenix Orchestrator system, specifically:
#   - Requires security-neuralink tests to pass before merging
#   - Prevents force pushes to protected branches
#   - Enforces code review by security team
#   - Logs any attempt to bypass these protections
#
# SECURITY NOTICE: Modifications to this file require security team approval.
# Any attempt to bypass these protections will be logged and investigated.

# Branch Protection Rules
protection:
  # Protected branch patterns
  branches:
    - main
    - develop
    - release/*
    - security/*
  
  # Required status checks
  required_status_checks:
    # Require branches to be up to date before merging
    strict: true
    
    # Status checks that must pass before merging
    contexts:
      - "Security Penetration Tests"
      - "Neuralink Hardware-in-Loop Tests"
      - "Security Pre-Check"
      - "Test Summary"
  
  # Required pull request reviews
  required_pull_request_reviews:
    # Dismiss stale pull request approvals when new commits are pushed
    dismiss_stale_reviews: true
    
    # Require approval from code owners
    require_code_owner_reviews: true
    
    # Required number of approvals
    required_approving_review_count: 2
    
    # Require approval from security team
    required_review_teams:
      - "security-team"
  
  # Include administrators in restrictions
  enforce_admins: true
  
  # Prevent force pushes
  allow_force_pushes: false
  
  # Prevent deletion of protected branch
  allow_deletions: false
  
  # Block creations (prevents naming a new branch the same name as an older deleted branch)
  block_creations: true
  
  # Restrict who can push to matching branches
  restrict_pushes:
    # Teams allowed to push to protected branches
    teams:
      - "developers"
      - "security-team"
      - "admins"

# Code Owners Configuration
# This section defines who owns which parts of the codebase
# and will be automatically requested for review when those files change
code_owners:
  # Security-critical code is owned by security team
  - pattern: "**/*.rs"
    owners:
      - "@security-team"
  
  # Critical test files require security team review
  - pattern: "tests/security_pentest.rs"
    owners:
      - "@security-team"
  
  - pattern: "tests/neuralink_hil.rs"
    owners:
      - "@security-team"
      - "@neuralink-team"
  
  # CI/CD configurations require security team approval
  - pattern: ".github/workflows/**"
    owners:
      - "@security-team"
      - "@devops-team"
  
  - pattern: ".github/branch-protection.yml"
    owners:
      - "@security-team"
      - "@devops-team"
  
  - pattern: ".github/test-environment.yml"
    owners:
      - "@security-team"
      - "@neuralink-team"

# Security Audit Logging
audit_logging:
  # Enable comprehensive audit logging
  enabled: true
  
  # Events to log
  events:
    - branch_protection_rules_modified
    - protected_branch_force_push_attempted
    - required_status_check_bypass_attempted
    - review_bypass_attempted
    - admin_bypass_attempted
  
  # Log retention period (days)
  retention_period: 90
  
  # Notification targets for audit events
  notification_targets:
    # Slack channel for immediate alerts
    slack_channels:
      - "#security-alerts"
    
    # Email for detailed reports
    email:
      - "security-team@example.com"

# Custom Security Settings
security_settings:
  # Zero tolerance for security bypass attempts
  security_bypass_tolerance: zero
  
  # Automated responses to protection bypass attempts
  bypass_attempt_responses:
    # Automatically lock branch on suspicious activity
    lock_branch: true
    
    # Create security incident report
    create_incident_report: true
    
    # Notify security team
    notify_security_team: true