/**
 * Incident Report Template
 * 
 * Template for generating security incident reports. This defines the structure,
 * sections, and formatting for incident reports generated by the Agentic SOC.
 */

module.exports = {
    name: 'Incident Report',
    id: 'incident_template',
    version: '1.0.0',
    description: 'Template for security incident reports',
    
    // Report metadata
    metadata: {
        classification: 'Internal',
        retention: '7 years',
        required: true
    },
    
    // Define sections and their order
    sections: [
        {
            id: 'executive_summary',
            title: 'Executive Summary',
            required: true,
            maxLength: 500,
            description: 'Brief overview of the incident, impact, and response'
        },
        {
            id: 'incident_details',
            title: 'Incident Details',
            required: true,
            subsections: [
                {
                    id: 'incident_type',
                    title: 'Type of Incident',
                    required: true
                },
                {
                    id: 'detection_details',
                    title: 'Detection Details',
                    required: true,
                    fields: [
                        {
                            id: 'detection_method',
                            title: 'Detection Method',
                            type: 'select',
                            options: [
                                'SIEM Alert',
                                'Threat Hunting',
                                'Vulnerability Scan',
                                'External Notification',
                                'User Report',
                                'Automated System'
                            ]
                        },
                        {
                            id: 'detection_time',
                            title: 'Detection Time',
                            type: 'datetime'
                        },
                        {
                            id: 'detection_source',
                            title: 'Detection Source',
                            type: 'text'
                        }
                    ]
                },
                {
                    id: 'incident_timeline',
                    title: 'Incident Timeline',
                    required: true,
                    type: 'timeline'
                }
            ]
        },
        {
            id: 'impact_assessment',
            title: 'Impact Assessment',
            required: true,
            subsections: [
                {
                    id: 'affected_systems',
                    title: 'Affected Systems',
                    type: 'list'
                },
                {
                    id: 'affected_data',
                    title: 'Affected Data',
                    type: 'list'
                },
                {
                    id: 'business_impact',
                    title: 'Business Impact',
                    type: 'text'
                },
                {
                    id: 'regulatory_impact',
                    title: 'Regulatory Considerations',
                    type: 'text'
                }
            ]
        },
        {
            id: 'technical_details',
            title: 'Technical Details',
            required: true,
            subsections: [
                {
                    id: 'attack_vectors',
                    title: 'Attack Vectors'
                },
                {
                    id: 'iocs',
                    title: 'Indicators of Compromise',
                    type: 'table',
                    columns: ['Type', 'Value', 'Description', 'Confidence']
                },
                {
                    id: 'mitre_att_ck',
                    title: 'MITRE ATT&CK Mapping',
                    type: 'mitre-matrix'
                }
            ]
        },
        {
            id: 'response_actions',
            title: 'Response Actions',
            required: true,
            subsections: [
                {
                    id: 'containment_measures',
                    title: 'Containment Measures'
                },
                {
                    id: 'eradication_steps',
                    title: 'Eradication Steps'
                },
                {
                    id: 'recovery_procedures',
                    title: 'Recovery Procedures'
                }
            ]
        },
        {
            id: 'root_cause_analysis',
            title: 'Root Cause Analysis',
            required: true
        },
        {
            id: 'recommendations',
            title: 'Recommendations',
            required: true,
            type: 'list'
        },
        {
            id: 'lessons_learned',
            title: 'Lessons Learned',
            required: false
        },
        {
            id: 'appendices',
            title: 'Appendices',
            required: false,
            subsections: [
                {
                    id: 'supporting_evidence',
                    title: 'Supporting Evidence'
                },
                {
                    id: 'related_incidents',
                    title: 'Related Incidents'
                },
                {
                    id: 'references',
                    title: 'References'
                }
            ]
        }
    ],
    
    // Visualization configurations
    visualizations: [
        {
            id: 'incident_timeline_chart',
            title: 'Incident Timeline',
            type: 'timeline',
            dataSource: 'incident_timeline',
            config: {
                showMilestones: true,
                colorCoding: true
            }
        },
        {
            id: 'affected_systems_diagram',
            title: 'Affected Systems Diagram',
            type: 'network_diagram',
            dataSource: 'affected_systems'
        },
        {
            id: 'attack_path_visualization',
            title: 'Attack Path Visualization',
            type: 'attack_path',
            dataSource: 'technical_details'
        }
    ],
    
    // Output format configurations
    outputFormats: {
        pdf: {
            template: 'incident_report_pdf.hbs',
            paperSize: 'a4',
            orientation: 'portrait',
            headerTemplate: 'incident_report_header.hbs',
            footerTemplate: 'incident_report_footer.hbs'
        },
        html: {
            template: 'incident_report_html.hbs',
            css: 'incident_report.css'
        },
        markdown: {
            template: 'incident_report_markdown.hbs'
        },
        json: {
            schema: 'incident_report_schema.json'
        }
    }
};